# DON'T TOUCH THIS FILE
openapi: 3.0.0

info:
  title: Beatza API Documentation
  version: 1.0.5
  description: |
    Will comply with the standard HTTP status code, and standard naming conventions
    References:
    - [HTTP Status Code Reference](https://restfulapi.net/http-status-codes/)
    - [API Naming Conventions](https://restfulapi.net/resource-naming/)

    [The main website Beatza URL](https://beatza.me)

    [Real footage of the backend teamleader when asked about the project](https://www.youtube.com/watch?v=YkTSEja2nng)

# General tag definitions
tags:
  - name: Authentication
    description: Provides secure user authentication including login, registration, access token issuance, and refresh token handling.
  - name: Profile-Management
    description: Endpoints for fetching and managing user profiles, including updating profile information, uploading profile pictures.
  - name: Settings
    description: Endpoints for managing user settings, including notification preferences, account settings, and application configurations.
  - name: Track Management
    description: All endpoints related to track management
  - name: Playlist Management
    description: All endpoints related to playlist management IF YOU SEE A PUBLIC API AND ITS TWIN, CALL THE NON-PUBLIC ONE IF THE USER IS LOGGED IN TO HANDLE BLOCKED LISTS PLEASE
  - name: Playback
    description: All endpoints related to playback functionality, like listening history.
  - name: Feed
    description: Operations for user feed, global search, trending tracks
  - name: Search
    description: Operations for user feed, global search, trending tracks
  - name: Social
    description: Endpoints for fetching and managing user following, followed lists and social networks.
  - name: Reposts
    description: Endpoints for fetching and managing reposts on tracks and playlists.
  - name: Likes
    description: Endpoints for liking tracks, playlists and reposts.
  - name: Comments
    description: Endpoints for fetching and managing comments on tracks.
  - name: Notifications
    description: Endpoints for fetching and managing notifications.
  - name: Message
    description: Endpoints for sending, receiving, and managing user messages.
  - name: Payment
    description:
      Endpoints for handling user payments and subscription management using Stripe.
      Includes creating and managing subscriptions, processing billing events,
      and receiving Stripe webhook notifications to update payment and
      subscription status in the system.
  - name: Admin Users
    description: All endpoints related to admin users
  - name: Admin Tracks
    description: All endpoints related to admin tracks
  - name: Admin Analytics
    description: All endpoints related to admin analytics
  - name: Admin Reports
    description: All endpoints related to admin reports

# Global JWT requirement, it is not required for the Authentication Service, I
# I manually remove it from the Authentication Service endpoints with JS
security:
  - cookieAuth: []
  - bearerAuth: []

# later we can add other security schemas, but for now this is good.
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: accessToken
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

# When we know the ip/URL of our server we will add a field to shit
servers:
  - url: https://beatza.me
    description: Production server
  - url: http://localhost:4123
    description: Local development server
