#!/bin/sh
#
# An example hook script to check the commit log message.
# Called by "git commit" with one argument, the name of the file
# that has the commit message.  The hook should exit with non-zero
# status after issuing an appropriate message if it wants to stop the
# commit.  The hook is allowed to edit the commit message file.
#
# To enable this hook, rename this file to "commit-msg".

# .git/hooks/commit-msg
MSG_FILE="$1"

COMMITTER_NAME=$(git config user.name)

if [ -z "$COMMITTER_NAME" ]; then
    printf "\n\x1b[31m Please configure your git user.name! So I can catch you later if you do something foolish. \x1b[0m\n\n"
    exit 1
fi

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

ORIGINAL_MSG=$(cat "$MSG_FILE")

# Rewrite message
echo "$COMMITTER_NAME | $BRANCH_NAME | $ORIGINAL_MSG" > "$MSG_FILE"
