#!/bin/sh

bash "$(dirname "$0")/doc-printing.sh"

echo "Running tests before push..."

npm run test
STATUS=$?

COMMITTER_NAME=$(git config user.name)

if [ -z "$COMMITTER_NAME" ]; then
    printf "\n\x1b[31m Please configure your git user.name! So I can catch you later if you do something foolish. \x1b[0m\n\n"
    exit 1
fi

if [ $STATUS -ne 0 ]; then
    printf "\n\x1b[31m AAAYYYYYOOOOOOOOOOOOOO!!!!!!!!! WHO LET BRO COOK!?\x1b[0m\n\n"
    printf "\n\x1b[31m I am watching you $COMMITTER_NAME \x1b[0m\n\n"
    cat "$(dirname "$0")/error-art.ans"
    printf "\n\x1b[31m Foolishness $COMMITTER_NAME, Foolishness.\x1b[0m\n\n"
    printf "\x1b[34m You really thought I'd let you push broken code?\x1b[0m\n"
    exit 1
fi

printf "\x1b[34m Tests passed. Proceeding with push.\x1b[0m\n"
exit 0